BOT_TOKEN = "PASTE_TELEGRAM_BOT_TOKEN_HERE"
ADMIN_TELEGRAM_IDS = "123456789,987654321"
DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/namoz_bot"
ALEMBIC_DATABASE_URL = "postgresql+psycopg://postgres:postgres@localhost:5432/namoz_bot"
DEFAULT_TIMEZONE = "Asia/Tashkent"
PRAYER_API_BASE_URL = "https://api.example.com/prayer-times"
